repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        description: "Checks the style of Markdown files"
        entry: markdownlint-cli2
        language: node
        files: \.md$
        types: [markdown]
        minimum_pre_commit_version: "1.15.0"
        additional_dependencies: ["markdownlint-cli2@0.18.1"]
  
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types: [python]
      - id: ruff-format
        types: [python]

  - repo: local
    hooks:
      - id: domain-markdown-fixes
        name: Domain Markdown Auto-fixes
        entry: python scripts/linting/md_fixes/run_all_md_fixes.py
        language: system
        files: docs/domains/.*\.md$
        pass_filenames: false
        args: ['.', 'identity']  # Modify domain as needed
      - id: forbid-frontmatter-title
        name: "Forbid front-matter title: (docs/)"
        entry: python scripts/validation/check_no_frontmatter_title.py
        language: system
        files: ^docs/.*\.md$
        pass_filenames: true
      - id: guard-nav-orphans
        name: "Guard: no pages outside nav (mkdocs)"
        entry: python scripts/validation/check_nav_orphans.py
        language: system
        files: ^docs/.*\.(md|yml)$
        pass_filenames: false
