extends: default
rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
  indentation: disable
  new-lines: disable
ignore: |
  site/
