name: Documentation Quality Checks

on:
  push:
    branches: [ master ]
    paths: [ 'documents/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'documents/**' ]
  workflow_dispatch:

jobs:
  documentation-checks:
    name: Documentation Linting and Validation
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: documents
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync
      
    - name: Cache pre-commit hooks
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('documents/.pre-commit-config.yaml') }}
        
    - name: Run pre-commit hooks
      run: uv run pre-commit run --all-files
      
    - name: Check navigation orphans
      run: uv run python scripts/validation/check_nav_orphans.py
      
    - name: Check for frontmatter titles
      run: uv run python scripts/validation/check_no_frontmatter_title.py
      
    - name: Test MkDocs build
      run: uv run mkdocs build --strict
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: documentation-site
        path: documents/site/
        retention-days: 7
